### ISSUE TITLE
template-component-demo这个包的peerDependencies要求的react的版本希望更新一下

### ISSUE THREAD

**Issue by callmeYe** [ice-lab/icepkg#273]
现在是15，希望更新到16.x || 17.x

**Comment by mark-ck** [comment]
+ 1 ，现在 npm install 会报错

![image](https://user-images.githubusercontent.com/44559440/159406776-f752abf6-0959-43e0-8fed-7537390d6956.png)

**Comment by imsobear** [comment]
已升级
