### ISSUE TITLE
Iceworks cli 品牌升级

### ISSUE THREAD

**Issue by fyangstudio** [ice-lab/icepkg#277]
* [ ] [iceworks-cli](https://www.npmjs.com/package/iceworks-cli) 迁移 AppWorks cli
* [ ] [iceworks-cli](https://www.npmjs.com/package/iceworks-cli) npm 包 deprecate 配置
* [ ] AppWorks VS Code 新增 Iceworks cli 功能
* [ ] ice-lab/iceworks-cli  仓库名 更新为 ice-lab/common-packages

**Comment by fyangstudio** [comment]
#276

**Comment by imsobear** [comment]
「 AppWorks VS Code 新增 Iceworks cli 功能」这个具体怎么做？还是说先不着急？

**Comment by imsobear** [comment]
「仓库名 更新为 appworks-cli ?」appworks cli 的代码迁移到 apptools 下面，ice-lab/iceworks-cli 改个名字即可（比如 ice-lab/common-packages）。

**Comment by fyangstudio** [comment]
> 「 AppWorks VS Code 新增 Iceworks cli 功能」这个具体怎么做？还是说先不着急？

一期改造：
* 把 Iceworks cli 的命令都 加入到 VS Code command 中
* 判断是 material 项目，则在 命令快速入口中 显示 Iceworks cli 命令
* init 命令的选项 使用 webview 可视化选择

后续紧跟 @maoxiaoke 物料组件 链路更新，也可以有 一键抽离 物料 之类的 功能

**Comment by imsobear** [comment]
@fyangstudio 这块可以再对下，我的建议是两种思路二选一：

1. CLI 平迁过去，保持品牌一致性，然后集成到 VS Code 里短期不做
2. 废弃 CLI，直接**重新梳理功能**然后集成到 VS Code 里

我不太赞同 CLI 平迁，然后把这些功能直接缝合到 VS Code 里，直接缝合到 VS Code 里对用户没什么价值，然后我们还有开发的工作量以及后续维护。

**Comment by imsobear** [comment]
Iceworks CLI 已经升级为 AppWorks CLI `@appworks/cli`
