### ISSUE TITLE
组件工程 TypeScript 模板使用 react-docgen-typescript 生成 api 文档

### ISSUE THREAD

**Issue by TopGrd** [ice-lab/icepkg#278]
# 概述
在创建组件工程选择模板时，根据语言类型（typescript or javascript）采用不同的API文档生成库。
* react+ts react-docgen-typescript
* react+js react-docgen

# 背景
目前组件工程的api文档解析生成采用的是react-docgen，但是对于typescript的用户来说，有个缺点是它不能解析其他文件引入的类型。如下

```tsx
interface AesCardProps extends CardCommonProps {
  /** Title for ExampleComponent. */
  title: string;
}

const AesCard = (props: AesCardProps) => {
  const {
    children,
    style,
    className,
    title,
    description,
    descIcon,
  } = props;
  return (
    <Card className={className} style={style}>
      <Header title={title} description={description} descIcon={descIcon} />
      {children}
    </Card>
  );
};
```
生成文档
![image](https://user-images.githubusercontent.com/4202848/153159733-d68e126f-1e86-4d5b-899c-b9286fed419e.png)

上述代码中只能解析到 title，对于其他从CardCommonProps中继承来的属性都会丢失。原因是 react-docgen 不支持解析从其他文件引入的类型定义。

# 方案设计
社区中有 react-docgen-typescript 对typescript开发的组件支持从其他文件引入的类型定义，但是它不支持 PropTypes。
![image](https://user-images.githubusercontent.com/4202848/153160125-7332f74c-fa20-47eb-b632-7bc23abeb68f.png)

为了同时更友好的支持 JS 和 TS 两种类型的组件工程，可以在创建组件工程时，根据选择语言的类型，采用不同的解析库来生成组件文档。
* react+ts react-docgen-typescript
* react+js react-docgen

**Comment by guoyunhe** [comment]
应该不难搞，就是在 parse 文件的时候按后缀换一下 parser。

**Comment by maoxiaoke** [comment]
@guoyunhe 还要考虑下要不要支持，react-docgen-typescript 并不是 react-docgen 的增强（比如不支持 propType），如果区分的话 ，用户在使用上可能会有困惑
