### ISSUE TITLE
Catalogue of www

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icepkg#304]
- 这是什么 - 介绍 @ice/pkg
  - 特性
    - 更快：代码使用 [swc](https://swc.rs/docs/configuration/swcrc) 编译和压缩，提升数倍编译速度。
    - 支持 bundle 和 transform 两种模式：提供多种场景解决方案
    - 零配置：无需任何配置，提供 TypeScript 和 React JSX 支持。
    - 面向未来：提供 es2017 产物，可打包出面向现代浏览器支持的产物。
    - 更强大的预览能力：默认使用 [Docusaurus](https://docusaurus.io/) 作为组件预览，文档生成方案。
- 安装
- 快速初始化
- 使用
  - 命令行
  - 使用配置文件
  - 组件开发
  - Node 模块开发
  - Library 开发
  - 代码压缩
  - 生成 sourcemap
  - 配置全局变量
  - Alias
- 文档预览
  - 如何书写文档
  - 文档结构
  - 文档排序
  - 代码块
- 插件开发
  - 修改默认配置
  - 注册新任务
- 完整配置项
- Contributing
- License

**Comment by imsobear** [comment]
- 关于：特性、使用场景、Changlog、参与贡献、问题反馈、其他方案迁移（链到 issue）
- 快速开始
- 指南
	- 配置文件
	- 工程能力：TypeScript、sourceMap、define、alias……
      - 文档预览
- 使用场景
	- 前端组件
	- 前端 Lib
	- Node 模块
- 参阅
	- 完整配置项：配置参数（...）
	- 插件开发：约束
