### ISSUE TITLE
RC-0 版本功能

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icepkg#308]
- [x] 产物输出以及配置 #306
  - [x] 输出标准 bundle 产物 
  - [x] define 设计 #307 
- [x] 品牌名更换为 `@ice/pkg` #309
- [x] 初始化模板升级 https://github.com/ice-lab/material-templates/pull/79
- [ ] 官网文档 #300 
- [ ] 业务方体验
  - [ ] ice-next
  - [ ] pwc
  - [ ] 集团内部用户

**Comment by imsobear** [comment]
- `@ice/pkg-cli` 改为 `@ice/pkg`

**Comment by imsobear** [comment]
官网文档有必要用 `@ice/pkg` + 插件吗？是不是直接用 docusaurus 就好了？

**Comment by imsobear** [comment]
组件预览这块需要产出一个完整的 RFC，加了这块的话下周是否能做完？

**Comment by maoxiaoke** [comment]
> 官网文档有必要用 `@ice/pkg` + 插件吗？是不是直接用 docusaurus 就好了？

这个问题不太大，基本能力都在的。主要还是文档内容

**Comment by maoxiaoke** [comment]
> 组件预览这块需要产出一个完整的 RFC，加了这块的话下周是否能做完？

嗯嗯，我今天尽量产出一个 RFC

**Comment by imsobear** [comment]
> > 官网文档有必要用 `@ice/pkg` + 插件吗？是不是直接用 docusaurus 就好了？
> 
> 这个问题不太大，基本能力都在的。主要还是文档内容

嗯 那的确是的，可以先梳理目录
