### ISSUE TITLE
类型声明文件的输出结构

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icepkg#330]
## 背景

类型声明文件目前大致可有两种输出结构。

1. 结构一：类型声明文件和源代码存放在一起

```shell
- es2017
  - add.js
  - add.d.ts
  - index.js
  - index.d.ts
```

这种的结构存在的问题是，`@ice/pkg` 可能输出多份产物，比如 esm、es2017，导致类型文件膨胀。

2. 结构二：类型声明文件单独存放，比如存在 `types` 文件夹下。

```shell
- types
  - add.d.ts
  - index.d.ts
```

这种的结构存在的问题是：对代码阅读不友好。比如，当我们定位到 `add.d.ts`，直接定位到 types 目录，而非源码目录。

**Comment by maoxiaoke** [comment]
个人比较倾向于结构一。

**Comment by SoloJiang** [comment]
在不影响构建速度的前提下，倾向方案一

**Comment by imsobear** [comment]
方案一阔以

**Comment by luhc228** [comment]
https://github.com/ice-lab/icepkg/pull/339 已支持
