### ISSUE TITLE
关于 bundle UMD 产物处理自身依赖行为的讨论

### ISSUE THREAD

**Issue by ChrisCindy** [ice-lab/icepkg#354]
对于 @ice/pkg 支持的不同场景，综合社区调研结果，结论为打包 UMD 产物时对于其依赖的处理应当不同：

## 1. Web Library 开发
默认打入所有依赖。确保依赖版本的稳定以及对于 UMD 产物使用最多的场景——脚本引入时最大程度的简单可用。

## 2. React/Rax 组件开发
打入除 react/react-dom/rax 等核心库外的全部依赖。对于 UI 框架生态组件，由于使用该组件必须引入核心 UI 框架（以及比如全局环境只能存在一个 Rax 实例的限制），因此综合体积考虑，external 掉 UI 框架依赖较为合理。

## 3. 搭建体系
根据依赖是否入库以决定是否打入依赖。

---

配置项中的 externals 默认值修改为 false，即包含依赖产物。

以上第 1、2 点的差异性通过用户初始化项目时的 build.config.ts 模板中配置 externals 体现，同时在文档中说明。用户也可自由修改，灵活配置。第 3 点通过单独的插件进行逻辑处理。

**Comment by ChrisCindy** [comment]
> 搭建体系是否打入依赖，由对应的接口服务确定是否已经入库。 对于 React/Rax 组件开发理论上除单实例的需要 externals 外，实践上对于已有 umd 产物的包也会进行 externals，比如依赖 antd 的业务组件一般会把 antd 也进行 externals 设置，需要在文档中给出一定的建议

OK，对于搭建体系的处理已修改。对于实践的部分在文档侧给出建议是合理的。同时也需要提醒用户对于 umd 产物的版本号的控制。

**Comment by maoxiaoke** [comment]
默认设置为 externals = false 的逻辑是什么呢？我其实更倾向于「不默认包含」。

+ UMD 是过渡性产物
+ 需要包含依赖的场景不多

**Comment by ChrisCindy** [comment]
> 默认设置为 externals = false 的逻辑是什么呢？我其实更倾向于「不默认包含」。
> 
> * UMD 是过渡性产物（不应该面向 UMD 模块规范设计）
> * 需要包含依赖的场景不多？

结论还是按上面的说法。在 es modules 尚未普及的情况下 bundle 默认包含依赖更合理。目前社区实践的 UMD 包默认都是包含依赖或者 external 掉框架依赖的。（另，externals 为 true 的话对于 rollup 而言，用户不配置 output.globals 其实同样有问题，这样对用户而言反而增加理解及排查成本）
