### ISSUE TITLE
组件工程 build-plugin-component 如果组件入参没有 props 并且没有定义 interface 的时候报错

### ISSUE THREAD

**Issue by luhc228** [ice-lab/icepkg#359]
如果有以下的代码：
```diff
import * as React from 'react';
import './index.css';

- interface ComponentProps {
- /** Title for ExampleComponent. */
- title: string;
-}

export default function ExampleComponent(
- props: ComponentProps
) {
  // const { title, ...others } = props;

  return (
    <div className="ExampleComponent">Hello ExampleComponent</div>
  );
}
```

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/44047106/175255762-8238986c-5115-49c6-9235-3bc1ea980db6.png">

初步判断是 props 是 Undefined，没有做兼容处理

<img width="795" alt="image" src="https://user-images.githubusercontent.com/44047106/175256011-3bcf6a11-e330-45f1-b9f6-70c29514902e.png">

**Comment by wssgcg1213** [comment]
这个解决了吗

**Comment by ChrisCindy** [comment]
本周更新后已无法复现，目测已修复
