### ISSUE TITLE
create-pkg 提供更多模板供用户使用

### ISSUE THREAD

**Issue by ChrisCindy** [ice-lab/icepkg#360]
create-pkg 目前仅提供 react component 一种模板，考虑扩展为三种模板供用户初始化时选择：

1. React Component
2. JS API
3. Rax Component

**Comment by ChrisCindy** [comment]
@ClarkXia @wssgcg1213

**Comment by wssgcg1213** [comment]
1. npm 包
2. React 组件
3. Rax 组件
