### ISSUE TITLE
组件中引用 index.module.less，启动报错

### ISSUE THREAD

**Issue by darkmice** [ice-lab/icepkg#368]
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/1502088/178442138-48e06bdb-6ebc-4063-a4c8-55baae7d6d4f.png">

**Comment by darkmice** [comment]
原因是 `@ice/pkg-plugin-docusaurus` 组件没有内置 ` docusaurus-plugin-less`，希望能加上这个插件，

**Comment by maoxiaoke** [comment]
@darkmice 是的，目前只支持了 scss 语法

**Comment by luhc228** [comment]
现在已支持
https://github.com/ice-lab/icepkg/blob/6cfc0182bffa60813e5d2ef66f0d84f76a7e54de/packages/plugin-docusaurus/src/template/docusaurus.hbs#L25
