### ISSUE TITLE
外部用户不应该出现这个 prompt

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icepkg#370]
![image](https://user-images.githubusercontent.com/13417006/179652264-ec1cc1ba-d5f2-4cf9-bcc2-c4c066eac89e.png)

**Comment by wssgcg1213** [comment]
这个提示是啥意思, 看不懂 @ChrisCindy

**Comment by imsobear** [comment]
> 这个提示是啥意思, 看不懂 @ChrisCindy

package name 是否加 `@ali` 的 prefix.

**Comment by imsobear** [comment]
> > 这个提示是啥意思, 看不懂 @ChrisCindy
> 
> package name 是否加 `@ali` 的 prefix.

代码上应该是只有内网网络才会出这个选项，可能有 bug

**Comment by wssgcg1213** [comment]
1. bug 修一下问题不大
2. 提示可以直接点, 就叫引入 def 插件或者啥玩意儿, 另外丢个文档

**Comment by maoxiaoke** [comment]
tql
