### ISSUE TITLE
plugin-doc 引入了一个额外的依赖，会导致文档编译报错

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/icepkg#372]
https://github.com/ice-lab/icepkg/pull/366/files/014f9c0e66635651141ba54f59edbfe943b90f80#diff-6e0a777d31a31d5696e07ce01f1645dc124465512de876faf497312df0349cc7R78

![image](https://user-images.githubusercontent.com/13417006/179675888-3da5ec67-5c37-4de3-82e0-a8182d6d158c.png)

**Comment by ChrisCindy** [comment]
安装一下该依赖。目前脚手架模板已经更新为添加了该依赖了。
