### ISSUE TITLE
Apple M1 芯片使用 pnpm，默认安装的 esbuild 版本不对，需要手动安装 esbuild-darwin-arm64

### ISSUE THREAD

**Issue by lbarakidouji** [ice-lab/icepkg#385]
按照官网《快速开始》
使用 pnpm 初始化项目
执行 `pnpm start` 的时候，会有如下报错：

![image](https://user-images.githubusercontent.com/83287204/186357561-557eb741-54f6-43b4-8c5f-11887eebc13f.png)

需要手动安装npm包：`esbuild-darwin-arm64` 才可以正常启动

node版本：16.14.0
电脑环境：MacOS
电脑芯片：Apple M1 Max

不知道是 esbuild 的问题还是 pnpm 的问题？还是我环境问题

**Comment by lbarakidouji** [comment]
有没有人啊.....

**Comment by ChrisCindy** [comment]
收到，我尽快排查一下问题

**Comment by lbarakidouji** [comment]
个人原因，清楚全局的 pnpm-store 后正常
