### ISSUE TITLE
启动存在ERROR：Bindings not found

### ISSUE THREAD

**Issue by lbarakidouji** [ice-lab/icepkg#386]
启动存在 ERROR
但是不影响正常启动

![image](https://user-images.githubusercontent.com/83287204/186358959-7fdf73c5-4f30-4d42-b922-d56e91a3e620.png)

**Comment by ChrisCindy** [comment]
和上一个 esbuild 是同一个问题吗？

**Comment by lbarakidouji** [comment]
> 

这是我手动装完esbuild之后，可以正常起来起来，但是会有这个ERROR

**Comment by wssgcg1213** [comment]
重新安装一下依赖会解决吗, 看起来是对应的 binding 找不到

**Comment by lbarakidouji** [comment]
> 重新安装一下依赖会解决吗, 看起来是对应的 binding 找不到

不行，感觉是和我上一个 issues 结合起来的问题：M1芯片安装 es-build 版本不对应问题
