### ISSUE TITLE
[RFC] 支持配置 JSX Runtime

### ISSUE THREAD

**Issue by luhc228** [ice-lab/icepkg#439]
## 背景

[New JSX Transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) 能力可以让开发者在编写 React 组件的时候不需要在文件的顶部引入 React，减少了组件开发的成本，并可能会减小 bundle 的体积大小。目前，在以下的 react 版本中支持该能力：

- react@^15.7.0\
- react@^16.14.0
- react@^17.0.0
- react@^18.0.0

@ice/pkg 的 transform 模式下，默认都是使用了 JSX Transform，编译出来的产物是直接依赖了 `react/jsx-runtime`。
但是有部分项目依赖的 react 版本过低，并没有导出 jsx-runtime，项目并没有升级到最新的 minor 版本的计划。

## 方案

https://github.com/ice-lab/icepkg/blob/6cfc0182bffa60813e5d2ef66f0d84f76a7e54de/packages/pkg/src/rollupPlugins/swc.ts#L35

bundle 模式下肯定是使用 classic，而 transform 模式下默认可以使用 automatic，开放 userConfig 支持配置：

```ts
// build.config.mts
import { defineConfig } from '@ice/pkg';

export default defineConfig({
  transform: {
    jsxRuntime: 'classic'
  }
})
```

或者是：

```ts
// build.config.mts
import { defineConfig } from '@ice/pkg';

export default defineConfig({
  transform: {
   automaticJsxRuntime: false
  }
})
```

**Comment by callmeYe** [comment]
投第一种方案一票，配置方式更清晰

**Comment by ClarkXia** [comment]
bundle 肯定是 classic 的原因是什么

**Comment by luhc228** [comment]
> bundle 肯定是 classic 的原因是什么

[icepkg/packages/pkg/src/rollupPlugins/swc.ts](https://github.com/ice-lab/icepkg/blob/6cfc0182bffa60813e5d2ef66f0d84f76a7e54de/packages/pkg/src/rollupPlugins/swc.ts#L35)

**Comment by luhc228** [comment]
最终方案是支持配置 jsxRuntime 的值，对 bundle 和 transform 都生效

// build.config.mts
import { defineConfig } from '@ice/pkg';

export default defineConfig({
    jsxRuntime: 'classic'
})
