### ISSUE TITLE
@ice/pkg 1.4.1 版本 构建报错roperty '${variables}' of exported interface has or is using private name '${internal object}'.

### ISSUE THREAD

**Issue by microTT** [ice-lab/icepkg#454]
Describe the bug
@ice/pkg 1.4.1版本报错如下图
![image](https://user-images.githubusercontent.com/6782488/216964834-a0476760-94af-44aa-a9de-e88b7831186d.png)

版本号锁定至1.4.0正常

Expected behavior
不报错

Actual behavior
No response

Version of ice.js
@ice/pkg 1.4.1

Content of build.json or ice.config.mts
No response

Additional context
No response

**Comment by luhc228** [comment]
自行检查 TS 的类型，本质上是用 tsc 生成类型的
