### ISSUE TITLE
使用 bundle模式，生成umd文件时，报错

### ISSUE THREAD

**Issue by lyj2209914083** [ice-lab/icepkg#512]
报错信息如下：
No name was provided for external module 'http' in output.globals – guessing 'require$$1'
No name was provided for external module 'https' in output.globals – guessing 'require$$2$1'
No name was provided for external module 'url' in output.globals – guessing 'require$$0$1'
No name was provided for external module 'stream' in output.globals – guessing 'require$$3'
报错截图如下：
<img width="672" alt="image" src="https://user-images.githubusercontent.com/70557762/227460418-f1d44bce-a958-4696-bc39-2b2f4af48762.png">

最后虽然成功生成了umd文件，但是使用时会报对应变量不存在的错误，截图如下：
<img width="655" alt="image" src="https://user-images.githubusercontent.com/70557762/227460960-97945a9a-98e1-49c6-89ae-7db53fcc3a6a.png">

**Comment by luhc228** [comment]
你的依赖中有 Node 原生模块（http/url 等），你可以试下加入这个插件：
https://www.npmjs.com/package/rollup-plugin-polyfill-node

不过 require$$1 这个应该是产物里的内容吧？
