### ISSUE TITLE
希望能支持本地开发时配置 host

### ISSUE THREAD

**Issue by rlog** [ice-lab/icepkg#533]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**

希望本地开发时可以支持自定义 host，目前默认取了本地 IP，有远程接口调用时调试不便

**Comment by luhc228** [comment]
支持配置 host 了
https://github.com/ice-lab/icepkg/blob/main/website/docs/guide/preview.md
