### ISSUE TITLE
ice/pkg没有对.d.ts文件做特殊处理

### ISSUE THREAD

**Issue by VirusPC** [ice-lab/icepkg#596]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
ice/pkg没有对.d.ts文件做特殊处理。
文件`A.ts`引用了文件`B.d.ts`，编译后`A.ts`文件会生成A.js，而`B.d.ts`不会生成`B.js`。这一步是合理的。
但是，生成的`A.js`代码里引用了不存在的`B.d.js`，这就不合理了。

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：ice/pkg@1.5.11
* Node verson：node@18.16.1  tnpm@9.14.2 
* Platform：MacOS

下图中`index.ts`对应`A.ts`，`types.d.ts`对应`B.d.ts`

编译前：
![image](https://github.com/ice-lab/icepkg/assets/30697592/2d904366-4635-4aa1-b8af-2bf58f0c9964)
![image](https://github.com/ice-lab/icepkg/assets/30697592/b6e25d6d-e2ad-4e0c-9d41-0428cb480488)

编译后：
![image](https://github.com/ice-lab/icepkg/assets/30697592/9901e2b8-4d7e-4c25-9fb9-a3ba77a01945)
![image](https://github.com/ice-lab/icepkg/assets/30697592/08fd008f-0166-4e9b-9ab9-89554da1c7ef)

**What is the expected behavior?**
生成的`A.js`代码里不应该引用`B.d.js`

**Comment by luhc228** [comment]
希望提供可复现 demo

**Comment by luhc228** [comment]
不要在 ts 文件中导出 d.ts 文件

**Comment by VirusPC** [comment]
是的，现在是把.d.ts文件改为.ts文件解决的呢。后续会支持在ts文件中导出.d.ts么？

**Comment by VirusPC** [comment]
是的，现在是把.d.ts文件改为.ts文件解决的呢。请问后续会支持在ts文件中导出.d.ts么～

**Comment by luhc228** [comment]
> 是的，现在是把.d.ts文件改为.ts文件解决的呢。请问后续会支持在ts文件中导出.d.ts么～

这种写法不推荐
