### ISSUE TITLE
配置了https和host后，终端里显示的地址和自动打开的页面地址和配置不一致

### ISSUE THREAD

**Issue by anyuxuan** [ice-lab/icepkg#598]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

配置：

server: https
host: 0.0.0.0
![image](https://github.com/ice-lab/icepkg/assets/24931869/35a8e4e9-96bd-4159-a87c-863c366d5766)

终端显示的地址和自动打开的页面地址是：
![image](https://github.com/ice-lab/icepkg/assets/24931869/380f4ef0-7984-4e4e-9fb8-624abc588c64)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**

期望终端显示地址和自动打开页面地址是：https://0.0.0.0:4000/

**Comment by luhc228** [comment]
<img width="645" alt="image" src="https://github.com/ice-lab/icepkg/assets/44047106/e0ae4eab-a402-4c1b-9f0a-b644f3773de7">

**Comment by luhc228** [comment]
https 得通过 docusaurus 插件修改 webpack dev server 的配置

https://pkg.ice.work/guide/preview/#plugins

**Comment by anyuxuan** [comment]
> https 得通过 docusaurus 插件修改 webpack dev server 的配置
> 
> https://pkg.ice.work/guide/preview/#plugins

谢啦，我之前是通过自定义plugin设置的https和host，我按照你截图的方式设置host没问题了
