### ISSUE TITLE
umd 模式下css bundle中多了很多冗余样式，求解！！！

### ISSUE THREAD

**Issue by hokage7th** [ice-lab/icepkg#601]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**

**Comment by hokage7th** [comment]
![image](https://github.com/ice-lab/icepkg/assets/38130413/2d4c9d38-2e48-4393-9176-0195f3bfe6b5)
![image](https://github.com/ice-lab/icepkg/assets/38130413/c18a6795-fbd1-446a-ba4a-448e807603f7)
 希望只保存esm生成结果一样的样式，有什么好的方法么

**Comment by luhc228** [comment]
> ![image](https://user-images.githubusercontent.com/38130413/273835554-2d4c9d38-2e48-4393-9176-0195f3bfe6b5.png) ![image](https://user-images.githubusercontent.com/38130413/273835638-c18a6795-fbd1-446a-ba4a-448e807603f7.png) 希望只保存esm生成结果一样的样式，有什么好的方法么

这两个图，一个是 js 文件，一个是 css 文件。我没太能看懂

**Comment by hokage7th** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hokage7th** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
