### ISSUE TITLE
开启 jsx-plus 插件后，内联 rpx 没有自动转成 vw

### ISSUE THREAD

**Issue by luhc228** [ice-lab/icepkg#623]
目前  ICEPKG 转换内联 rpx 是通过 `@ice/jsx-runtime` 转换的，但是 jsx-plus 目前仅能转成 classic 模式 jsx-runtime

**Comment by wssgcg1213** [comment]
jsx-plus 插件启用的时候可以指定 createElement 方法 import 的来源

**Comment by wssgcg1213** [comment]
但是 jsx-plus 本身应该不涉及转换 JSX 的逻辑

**Comment by luhc228** [comment]
> jsx-plus 插件启用的时候可以指定 createElement 方法 import 的来源

怎么设置吗？
