### ISSUE TITLE
打包成umd格式的js文件  里面的中文乱码

### ISSUE THREAD

**Issue by Jerryqun** [ice-lab/icepkg#634]
打包成umd格式的js文件  里面的中文乱码

https://dev.g.alicdn.com/code/npm/@ali/flyfoxsdk/0.1.0/index.umd.es5.production.js

![image](https://github.com/ice-lab/icepkg/assets/26621285/3b25cc81-7af6-4520-8841-4333b80aaa87)

**Comment by luhc228** [comment]
跟浏览器的 编码方式有关。你可以在本地用 UTF-8 编码方式打开

**Comment by Jerryqun** [comment]
> 跟浏览器的 编码方式有关。你可以在本地用 UTF-8 编码方式打开

![image](https://github.com/ice-lab/icepkg/assets/26621285/8943ef93-6037-4077-8c19-61951da71432)
我复制出来在vscode里面打开也是一样的。
