### ISSUE TITLE
Docusaurus插件如何配置插件属性？

### ISSUE THREAD

**Issue by isunkui** [ice-lab/icepkg#640]
我想给文档预览服务配置搜索插件，现在插件的配置好像不支持设置插件的默认属性？

plugins的配置不支持解析数组格式的语法

[https://github.com/easyops-cn/docusaurus-search-local](docusaurus-search-local)

## 插件配置文档
```
import { defineConfig } from '@ice/pkg';

export default defineConfig({
  plugins: [
    [
      '@ice/pkg-plugin-docusaurus', 
      {
        plugins: [
          // 你也可以添加插件包
          '@easyops-cn/docusaurus-search-local',
        ]
      },
    ],
  ],
});
```

**Comment by luhc228** [comment]
你可以在根目录下创建 `docusaurus.config.js` 自定义配置的

**Comment by luhc228** [comment]
也可以通过这种方式传入：
```js
import { defineConfig } from '@ice/pkg';

export default defineConfig({
  plugins: [
    [
      '@ice/pkg-plugin-docusaurus', 
      {
        plugins: [
          // 你也可以添加插件包
-         '@easyops-cn/docusaurus-search-local',
+         ['@easyops-cn/docusaurus-search-local', { /* your options */ }]
        ]
      },
    ],
  ],
});
```

**Comment by isunkui** [comment]
> 也可以通过这种方式传入：
> 
> ```diff
> import { defineConfig } from '@ice/pkg';
> 
> export default defineConfig({
>   plugins: [
>     [
>       '@ice/pkg-plugin-docusaurus', 
>       {
>         plugins: [
>           // 你也可以添加插件包
> -         '@easyops-cn/docusaurus-search-local',
> +         ['@easyops-cn/docusaurus-search-local', { /* your options */ }]
>         ]
>       },
>     ],
>   ],
> });
> ```

目前就是按照文档说的这种方式报错了才反馈的哈，我试试你说的第一种方式创建 `docusaurus.config.js` 验证一下

目前用到的版本号：
- @ice/pkg@1.5.19
- @docusaurus+core@2.4.3

```
[ERROR] Error: Cannot find module '@easyops-cn/docusaurus-search-local,[object Object]'
...
[INFO] Docusaurus version: 2.4.3
Node version: v16.17.1
```
